# Generated by Django 5.2.10 on 2026-01-19 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectot_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(db_index=True, unique=True)),
                ('ticker', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='analytics.sector')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('report_type', models.CharField(choices=[('RATIOS', 'Financial Ratios'), ('GROWTH', 'Growth Metrics'), ('INDUSTRY', 'Industry Benchmarks'), ('INCOME_ST', 'Income Statement'), ('BALANCE_SH', 'Balance Sheet')], db_index=True, max_length=20)),
                ('period', models.CharField(choices=[('ANNUAL', 'Annual'), ('QUARTERLY', 'Quarterly'), ('TTM', 'Trailing Twelve Months')], default='ANNUAL', max_length=20)),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('net_profit', models.BigIntegerField(blank=True, null=True)),
                ('eps', models.FloatField(blank=True, null=True)),
                ('roe', models.FloatField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='analytics.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'report_type', 'year'], name='analytics_f_company_7fd4c4_idx')],
                'unique_together': {('company', 'year', 'report_type', 'period')},
            },
        ),
        migrations.CreateModel(
            name='StockPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('open_val', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('pe_live', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='analytics.company')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('company', 'date')},
            },
        ),
    ]
