# Generated by Django 5.2.10 on 2026-01-19 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sector',
            old_name='sectot_id',
            new_name='sector_id',
        ),
    ]
